import { abrir, recorte } from "./ms-lib.mjs";
const { nav, ctx, pg, monta, err } = await abrir();
const O = "manual-sider/img/";
const foto = (n) => recorte(pg, O + n + ".png");
/* ---------- CERTIFICAR ---------- */
await monta("m=certificar", 390, 900);
await foto("c01-inicio");
await ctx.clearPermissions();
await pg.click("text=Activar mi ubicación"); await pg.waitForTimeout(500);
await foto("c01-negada");
await ctx.grantPermissions(["geolocation"], { origin: "https://arnes.local" });
await monta("m=certificar", 390, 900);
await pg.click("text=Activar mi ubicación"); await pg.waitForTimeout(800);
await foto("c02-ubicacion");
await pg.click("button:has-text('Seguir')"); await foto("c03-origen");
await pg.click("button:has-text('Apartadó')"); await foto("c04-material");
await pg.click("button:has-text('Botella marrón 250 cc')");
await pg.click("button:has-text('Costeñita Ámbar 330 cc')");
await foto("c04-material-dos");
await pg.fill('input[aria-label="Estibas de Botella marrón 250 cc"]', "40");
await pg.fill('input[aria-label="Estibas de Costeñita Ámbar 330 cc"]', "10");
await foto("c04-material-listo");
/* con un material sin factores */
await pg.click("button:has-text('Caja plástica azul')");
await pg.fill('input[aria-label="Estibas de Caja plástica azul"]', "5");
await foto("c04-sinfactores");
await pg.click("button:has-text('Caja plástica azul')");
await pg.locator(".ct-botones .btn").first().click();
await foto("c05-carga-vacio");
await pg.fill('.ct-campos input[placeholder="JYN141"]', "jyn141");
await foto("c05-carga");
await pg.click("button:has-text('Seguir a las fotos')"); await foto("c06-fotos-vacio");
const fi = await pg.$$(".ct-foto input[type=file]");
await fi[0].setInputFiles("manual-sider/foto/izq.jpg"); await pg.waitForTimeout(700);
await foto("c06-fotos-una");
await fi[1].setInputFiles("manual-sider/foto/der.jpg"); await fi[2].setInputFiles("manual-sider/foto/placa.jpg"); await pg.waitForTimeout(1200);
await foto("c06-fotos-tres");
await pg.click("button:has-text('Seguir a guardar')"); await foto("c07-guardar");
await pg.click("button:has-text('Guardar la ficha')"); await pg.waitForSelector("text=Ficha guardada"); await foto("c08-listo");
await monta("m=certificar&f=1", 390, 900);
await pg.locator(".ct-fichas").screenshot({ path: O + "c09-mis-fichas.png" });
/* ---------- DAR SALIDA ---------- */
await monta("m=salida&c=facturador", 390, 3000);
await pg.locator(".ds-ficha").nth(0).screenshot({ path: O + "d01-ficha.png" });
await pg.locator(".ds-ficha").nth(0).locator("input").fill("7687019429");
await pg.locator(".ds-ficha").nth(0).screenshot({ path: O + "d02-factura.png" });
await pg.locator(".ds-ficha").nth(2).screenshot({ path: O + "d03-faltan-fotos.png" });
await monta("m=salida&c=facturador", 1100, 1100); await foto("d04-pc");
await monta("m=salida&c=creador", 390, 1800); await foto("d05-sin-permiso");
/* ---------- EN TRÁNSITO: UN CAMIÓN CON VARIOS MATERIALES ---------- */
await monta("m=transito&c=multi-ai", 390, 1800);
await pg.locator("article.tr-vh").first().screenshot({ path: O + "t10-multi.png" });
console.log(err);
await nav.close();
